name: my first test CI/CD

on:
  push:
    branches:
      - master


jobs:
  my_first_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say Hi with echo
        run: |
          echo "Hi from first job!!"